{% set name = "hdf5tools" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e938aecef413bf37747044d1ef34458419717d0aafe639b55ebddcefd4012ae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=3.8
    - setuptools
    - hatchling
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - xarray >=2022.03.0
    - h5py >=3.6.0
    - hdf5plugin >=3.3.1
    - cftime

test:
  imports:
    - hdf5tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mullenkamp/hdf5-tools
  summary: Python hdf5 tools
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mullenkamp
